### ISSUE TITLE
In the new season of apex AutoExec causes the game to crash.

### ISSUE THREAD

**Issue by Urafkard** [Natram1zh/Apex-Legends-Config-And-Tweaks#3]
Game crashes when I have the `developer "1"` uncomented after commenting the line I don't get the error.
Error bellow
![r5apex_wGwFHWsr16](https://user-images.githubusercontent.com/37073789/167695936-9bc8a0f5-d210-47f6-bb61-193ad321086b.png)

**Comment by rstewa35** [comment]
comment out line 30 in `autoexec.cfg` to fix it

it's this line that's causing the exception: `developer "1"                                                           // Developer mode (Shows dev time)(Works)`.

**Comment by Natram1zh** [comment]
Thank you so much.
