### ISSUE TITLE
30 fps cap

### ISSUE THREAD

**Issue by cronner** [Natram1zh/Apex-Legends-Config-And-Tweaks#5]
After changing to these files from others I used I tried several times that the game gets capped at 30 fps mid game, only Apex restart helps

**Comment by Natram1zh** [comment]
Did you use exec superglide.cfg? If yes then add "//" infront of the command, go to %USERPROFILE%\Saved Games\Respawn\Apex\local open settings.cfg then check for this binds and remove it "MWHEELUP" "+jump; fps_max 30; exec superglide2.cfg" 0, bind "MWHEELUP" "+duck; fps_max 0; exec superglide.cfg" 0 and  bind_US_standard "SPACE" "+jump; exec superglide1.cfg" 0. 
![image](https://user-images.githubusercontent.com/83518657/169667155-5cbeacbb-8338-4841-bf4b-99e844e9b724.png)

Movement scripts are for advanced users only, if you want to learn about it then watch this video 👇
https://youtu.be/N2-wHgQFJSI

Read this before you change it 🙏
![image](https://user-images.githubusercontent.com/83518657/169667485-041afd3c-f28b-45b6-a9f7-7d09e3509dc0.png)
