### ISSUE TITLE
video config not working

### ISSUE THREAD

**Issue by takaqiao** [Natram1zh/Apex-Legends-Config-And-Tweaks#7]
not sure its cuz the new NVIDIA driver or not
some config will revert to default(maybe,not sure wats the default look like) and read-only is not working(not sure but the model is absolutly more prettier than before).

**Comment by Natram1zh** [comment]
For me it works fine 
I am using 522.25 [Driver version]
In-Game Lowest Settings : videoconfig-default.txt
[videoconfig-default.txt](https://github.com/Natram1zh/Apex-Legends-Config-And-Tweaks/files/9989431/videoconfig-default.txt)
My current settings [Using DX12 so borderless window will be enabled] : videoconfig.txt
[videoconfig - default.txt](https://github.com/Natram1zh/Apex-Legends-Config-And-Tweaks/files/9989383/videoconfig.-.default.txt)

**Comment by takaqiao** [comment]
Yea Im using the newest right now, 526.86 I will try ur config posted above to see if it works or not.

**Comment by takaqiao** [comment]
btw its the problem I met right now(still testing the new one)just leave the code here as record.
The one using ur main github config(just change the resoultion)
`"VideoConfig"
{
	"setting.cl_gib_allow"		"0"
	"setting.cl_particle_fallback_base"		"3"
	"setting.cl_particle_fallback_multiplier"		"2"
	"setting.cl_ragdoll_maxcount"		"0"
	"setting.cl_ragdoll_self_collision"		"0"
	"setting.mat_forceaniso"		"0"
	"setting.mat_mip_linear"		"0"
	"setting.stream_memory"		"160000"
	"setting.mat_picmip"		"2"
	"setting.particle_cpu_level"		"0"
	"setting.r_createmodeldecals"		"0"
	"setting.r_decals"		"0"
	"setting.r_lod_switch_scale"		"0.4"
	"setting.shadow_enable"		"0"
	"setting.shadow_depth_dimen_min"		"0"
	"setting.shadow_depth_upres_factor_max"		"0"
	"setting.shadow_maxdynamic"		"0"
	"setting.ssao_enabled"		"0"
	"setting.ssao_downsample"		"3"
	"setting.dvs_enable"		"0"
	"setting.dvs_gpuframetime_min"		"15000"
	"setting.dvs_gpuframetime_max"		"16500"
	"setting.nowindowborder"		"0"
	"setting.fullscreen"		"1"
	"setting.defaultres"		"2560"
	"setting.defaultresheight"		"1440"
	"setting.volumetric_lighting"		"0"
	"setting.volumetric_fog"		"0"
	"setting.mat_vsync_mode"		"0"
	"setting.mat_backbuffer_count"		"1"
	"setting.mat_antialias_mode"		"0"
	"setting.csm_enabled"		"0"
	"setting.csm_coverage"		"1"
	"setting.csm_cascade_res"		"0"
	"setting.fadeDistScale"		"1.000000"
	"setting.dvs_supersample_enable"		"0"
	"setting.new_shadow_settings"		"1"
	"setting.gamma"		"1.000000"
	"setting.configversion"		"7"
}`
After launch the game it will auto change to the
`"VideoConfig"
{
	"setting.cl_gib_allow"		"0"
	"setting.cl_particle_fallback_base"		"9999999"
	"setting.cl_particle_fallback_multiplier"		"9999999"
	"setting.cl_ragdoll_maxcount"		"0"
	"setting.cl_ragdoll_self_collision"		"0"
	"setting.mat_forceaniso"		"0"
	"setting.mat_mip_linear"		"0"
	"setting.stream_memory"		"160000"
	"setting.mat_picmip"		"2"
	"setting.particle_cpu_level"		"0"
	"setting.r_createmodeldecals"		"0"
	"setting.r_decals"		"0"
	"setting.r_lod_switch_scale"		"0.4"
	"setting.shadow_enable"		"0"
	"setting.shadow_depth_dimen_min"		"0"
	"setting.shadow_depth_upres_factor_max"		"0"
	"setting.shadow_maxdynamic"		"0"
	"setting.ssao_enabled"		"0"
	"setting.ssao_downsample"		"3"
	"setting.dvs_enable"		"0"
	"setting.dvs_gpuframetime_min"		"15000"
	"setting.dvs_gpuframetime_max"		"16500"
	"setting.nowindowborder"		"0"
	"setting.fullscreen"		"1"
	"setting.defaultres"		"2560"
	"setting.defaultresheight"		"1440"
	"setting.volumetric_lighting"		"0"
	"setting.volumetric_fog"		"0"
	"setting.mat_vsync_mode"		"0"
	"setting.mat_backbuffer_count"		"1"
	"setting.mat_antialias_mode"		"0"
	"setting.csm_enabled"		"0"
	"setting.csm_coverage"		"1"
	"setting.csm_cascade_res"		"0"
	"setting.fadeDistScale"		"1.000000"
	"setting.dvs_supersample_enable"		"0"
	"setting.new_shadow_settings"		"1"
	"setting.gamma"		"1.000000"
	"setting.configversion"		"7"
}`

**Comment by takaqiao** [comment]
I just tried the new one (lowest one)
the cl_particle_fallback_base cl_particle_fallback_multiplier changed to 9999999 mat_forceaniso changed to 0 r_lod_switch_scale changed to 0.4 automatically.

**Comment by takaqiao** [comment]
I just tested the another one (ur current one)
cl_particle_fallback_base cl_particle_fallback_multiplier changed to 9999999 and nowindowborder changed to 0
so weird.

**Comment by Natram1zh** [comment]
What is wrong in that? cl_particle_fallback_base and cl_particle_fallback_multiplier changes to 9999999 because of the autoexec. Rest of them are same

**Comment by Natram1zh** [comment]
Autoexec has some videoconfig commands in it 
Like command line 190,191,192,194,214,219,251,252,303...etc

**Comment by Natram1zh** [comment]
Yeah respawn may have updated the graphic [Like new insane settings for shadow]

**Comment by Natram1zh** [comment]
Anyways thanks for reporting, honesty I didn't feel change in graphic may be you have noticed it on 2k monitor
