### ISSUE TITLE
Unstable server connection and failing internet connection

### ISSUE THREAD

**Issue by miospruit** [Natram1zh/Apex-Legends-Config-And-Tweaks#9]
Hi,
recently, about 1 or 2 updates ago, i have been having internet issues during and after playing apex legends. 
If i play without the autoexec file from this github repo, i have no issues with dropping internet connection.
I was wondering, are there any other players who experience this? And could it be because of one of the values from connection settings within autoexec.cfg? 
I'm not really familiar with these settings, but i have some experience in networking, game dev and programming. So any help would be awsome! thanks in advance!

**Comment by Natram1zh** [comment]
I can't help you in this, apex servers are really unstable so...
If you have any problem, you can always add "//" infront of the commands to take no effect

telemetry_client_enable "0"                                             // Disable telemetry (Works)
telemetry_client_sendInterval "0"                                       // How often to send telemetry data (Works)
pin_opt_in "0"                                                          // Disable sending PIN telemetry data to EA (Works)
pin_plat_id "0"                                                         // Opts out of Respawn Data surveys (Works)
voice_forcemicrecord "0"                                                // Denys recording of comms to the server (Works)
//cl_resend "2"                                                           // Time of sending the next packet to the server in case of loss of the previous one (Works)
//cl_cmdbackup "4"                                                        // Number of backup usercmds to send to cover packet loss from client-> server (Works)
//cl_lagcompensation "1"                                                  // Performs server side lag compensation (Works)
//cl_smooth "1"                                                           // Enable show predictive error smoothing (Works)
//cl_smoothtime "0.01"                                                    // Time (sec.) client smoothing from prediction errors (Works)
//projectile_prediction "1"                                               // Enable client-side prediction and projectile projectile compensation (Works)
//projectile_predictionErrorCorrectTime "0.1"                             // Time during which projectile prediction errors are corrected (Works)
//cl_matchmaking_timeout "100"                                            // Raise base matchmaking timeout to decrease potential timeouts (Works)
//cl_ranked_reconnect_timeout "300"                                       // Sync to reconnect timeout to allow max reconnectable time (Works)
rate "1280000"                                                          // Maximum number of transmitted bytes per second from servers (Placebo)
//origin_presense_updateRate "20"                                         // Relax seconds between each Origin prescence update (Placebo)
//cl_cmdrate "20"                                                         // Number of updates to information about yourself on the server per second (Placebo)
//cl_updaterate_mp "20"                                                   // The number of requests to update the game world from the server per second (Placebo)
//host_limitlocal "1"                                                     // Apply cl_cmdrate and cl_updaterate to close the connection (Placebo)
//net_compresspackets "1"                                                 // Compress the packets sent to the server (Placebo)
//net_compresspackets_minsize "128"                                       // Compress packages not lower than the set value (Placebo)
//net_maxcleartime "0.020346"                                             // Reduce amount of time the engine can wait to send another packet (Placebo)
